[[contents]]
name = "신동"
desc = "맛있다"
x = 37.485506
y = 126.806288
tags=["돈가스","일식","비쌈"]

[[contents]]
name = "메밀꽃 필 무렵"
desc = "맛없다"
x = 37.485575
y = 126.804591
tags=["돈가스", "한식", "적당"]

[[contents]]
name = "크라이 치즈버거"
desc = "맛있다"
x = 37.485403
y = 126.806007
tags=["패스트푸드", "적당"]
